#FSR Autogenerated Content. DO NOT DELETE
from .operations import (  # pylint: disable=E0402
    query_ip, query_domain, query_host, query_file, download_predictions,
    check_api_health)

supported_operations = {
    'query_ip': query_ip,
    'query_domain': query_domain,
    'query_host': query_host,
    'query_file': query_file,
    'download_predictions': download_predictions,
    'check_api_health': check_api_health,
}