name: Create ZIP from develop Branch

on:
  push:
    branches:
      - develop  

jobs:
  package-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          ZIP_NAME="augur-preemptive-detection.zip"  
          echo "Creating zip file: $ZIP_NAME"
          zip -r "$ZIP_NAME" . \
          -x ".git/*" \
          -x ".gitignore" \
          -x ".github" \
          -x ".github/*"

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: augur-preemptive-detection
          path: augur-preemptive-detection.zip