name: Create TGZ from develop Branch

on:
  push:
    branches:
      - develop  

jobs:
  package-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create TGZ file
        run: |
          TAR_NAME="augur-preemptive-detection.tgz"
          echo "Creating tarball: $TAR_NAME"
          
          # This command compresses the folder and excludes git/github files
          tar -czf "$TAR_NAME" \
            --exclude=".git" \
            --exclude=".gitignore" \
            --exclude=".github" \
            augur-preemptive-detection

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: augur-preemptive-detection
          path: augur-preemptive-detection.tgz